#!/bin/bash

rm RunToTreat_AutoGenerated.txt
rm ./Reaction/Auto.reaction
rm ./Detector/Auto.detector
rm ../../Outputs/Analysis/Sim_GRIT*
rm ../../Outputs/Simulation/GRIT*

#=====================================================

beam=$1; target=$2; light=$3; heavy=$4; beamE=$5;
nRing=$7; nSect=$8; thick=$(echo "scale=3; $6/1000" | bc -l)
targT=$9

echo "Beam energy = "$beamE

nBeam=$(echo $beam | tr -dc '0-9')
nHeavy=$(echo $heavy | tr -dc '0-9')

#=====================================================

if [ "${13}" = "oneDet" ];
then
  name="R2699_Q01R"$nRing"S"$nSect"_T"$6"_"$beamE"MeV_TargT"$9"_"${11}"_oneDet"
else
  name="R2699_Q01R"$nRing"S"$nSect"_T"$6"_"$beamE"MeV_TargT"$9"_"${11}
fi

if [ "$target" = "2H" ];
then
  targetmaterial="CD2"
  if [ "$light" = "1H" ];
  then
    reacLong="dp"
    echo "Attempting (d,p), setting reacLong = "$reacLong
  elif [ "$light" = "3H" ];
  then
    reacLong="dt"
    echo "Attempting (d,t), setting reacLong = "$reacLong
  fi
elif [ "$target" = "1H" ];
then
  targetmaterial="CH2"
  if [ "$light" = "2H" ];
  then
    reacLong="pd"
    echo "Attempting (p,d), setting reacLong = "$reacLong
  elif [ "$light" = "3H" ];
  then
    reacLong="pt"
    echo "Attempting (p,t), setting reacLong = "$reacLong
  fi
elif [ "$target" = "3H" ];
then
    reacLong="tp"
    echo "Attempting (t,p), setting reacLong = "$reacLong
fi


echo "Input 11 = "${11}
echo "If empty, check that beamE properly defined from MeVu..."


if [ "${11}" = "flat" ];
then
  #csec="flat.txt"
  csec="flat_forGRIT.txt"
else
  #csec="GRIT_"$beam$reacLong"_"${11}"_8MeVu_Full.txt"
  csec="GRIT_"$beam$reacLong"_"${11}".txt"
  #csec="GRIT_"$beam$reacLong"_"${11}"_10MeVu_Full.txt"
  #csec="GRIT_"$beam$reacLong"_"${11}"_10MeVu_LowAnglesOnly.txt"
  #echo "USING LOW ANGLE ONLY CROSS SECTION!!!!!!!!!!!!!!!! MAKE SURE I WANT TO DO THIS!!"
  #echo "USING LOW ANGLE ONLY CROSS SECTION!!!!!!!!!!!!!!!! MAKE SURE I WANT TO DO THIS!!"
  #echo "USING LOW ANGLE ONLY CROSS SECTION!!!!!!!!!!!!!!!! MAKE SURE I WANT TO DO THIS!!"
  #echo "USING LOW ANGLE ONLY CROSS SECTION!!!!!!!!!!!!!!!! MAKE SURE I WANT TO DO THIS!!"
  #echo "USING LOW ANGLE ONLY CROSS SECTION!!!!!!!!!!!!!!!! MAKE SURE I WANT TO DO THIS!!"
  #echo "USING LOW ANGLE ONLY CROSS SECTION!!!!!!!!!!!!!!!! MAKE SURE I WANT TO DO THIS!!"
  #echo "USING LOW ANGLE ONLY CROSS SECTION!!!!!!!!!!!!!!!! MAKE SURE I WANT TO DO THIS!!"
  #echo "USING LOW ANGLE ONLY CROSS SECTION!!!!!!!!!!!!!!!! MAKE SURE I WANT TO DO THIS!!"
  #echo "USING LOW ANGLE ONLY CROSS SECTION!!!!!!!!!!!!!!!! MAKE SURE I WANT TO DO THIS!!"
fi

echo "======================="
echo $csec

#longcsec="~/Programs/nptool/Inputs/CrossSection/"$csec
#
#if [ ! -f $longcsec ];
#then
#  echo "File DOES NOT exist!"
#  exit 1
#fi


echo "======================="

#=====================================================

mvname="./"$beam$target"-"$light$heavy"/SAHF_"$name".root"
#mvname2="./"$beam$target"-"$light$heavy"/Sim_"$name".root"
mvname2="/media/charlottepaxman/Elements/ActiveWork/"$beam$target"-"$light$heavy"/Sim_"$name".root"
nameconstruct="GRIT_"$beam$target"-"$light$heavy"_"$name

dfile="./Detector/Auto.detector"
rfile="./Reaction/Auto.reaction"

#E=$(echo "scale=3; $2/1000" | bc -l)
E=0;
#E=4;

if (($nBeam < $nHeavy));
then
  echo "BEAM < HEAVY THEREFORE BACKWARDS";
  pos10=-165
  pos11=-170
  pos12=-175
  pos13=-180
  backwards=true
else
  echo "BEAM >= HEAVY THEREFORE FORWARDS";
  pos10=165
  pos11=170
  pos12=175
  pos13=180
  backwards=false
fi

#Boilerplate
sp=" "
echo -e "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" 		  >> ./Reaction/Auto.reaction
echo -e "Beam" 						  >> ./Reaction/Auto.reaction
echo -e "$sp""Particle=""$sp""$beam" 			  >> ./Reaction/Auto.reaction
echo -e "$sp""ExcitationEnergy=""$sp""0""$sp""MeV" 	  >> ./Reaction/Auto.reaction
echo -e "$sp""Energy=""$sp""$beamE""$sp""MeV" 		  >> ./Reaction/Auto.reaction
echo -e "$sp""SigmaEnergy=""$sp""0.0""$sp"" MeV" 	  >> ./Reaction/Auto.reaction
echo -e "$sp""SigmaThetaX=""$sp""0.0""$sp""deg" 	  >> ./Reaction/Auto.reaction
echo -e "$sp""SigmaPhiY=""$sp""0.0""$sp""deg"	 	  >> ./Reaction/Auto.reaction
echo -e "$sp""SigmaX=""$sp""2.0""$sp""millimeter" 	  >> ./Reaction/Auto.reaction
echo -e "$sp""SigmaY=""$sp""2.0""$sp""millimeter"	  >> ./Reaction/Auto.reaction
echo -e "$sp""MeanThetaX=""$sp""0""$sp""deg"	  	  >> ./Reaction/Auto.reaction
echo -e "$sp""MeanPhiY=""$sp""0""$sp""deg" 		  >> ./Reaction/Auto.reaction

#Define XY of given XYZT date
echo -e "$sp""MeanX=""$sp""+0.00""$sp""millimeter" 	  >> ./Reaction/Auto.reaction
echo -e "$sp""MeanY=""$sp""+0.00""$sp""millimeter" 	  >> ./Reaction/Auto.reaction
echo -e "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" 		  >> ./Reaction/Auto.reaction
echo -e "TwoBodyReaction" 				  >> ./Reaction/Auto.reaction
echo -e "$sp""Beam=""$sp""$beam"			  >> ./Reaction/Auto.reaction

#Define reaction
echo -e "$sp""Target=""$sp""$target" 			  >> ./Reaction/Auto.reaction
echo -e "$sp""Light=""$sp""$light" 			  >> ./Reaction/Auto.reaction
echo -e "$sp""Heavy=""$sp""$heavy" 			  >> ./Reaction/Auto.reaction

#Define heavy recoil excitation & finish
echo -e "$sp""ExcitationEnergyLight=""$sp""0.0""$sp""MeV" >> ./Reaction/Auto.reaction
echo -e "$sp""ExcitationEnergyHeavy=""$sp""$E""$sp""MeV"  >> ./Reaction/Auto.reaction
if $backwards;
then
  echo -e "$sp""LabCrossSectionPath=""$sp""$csec""$sp""CSR"    >> ./Reaction/Auto.reaction
else
  echo -e "$sp""CrossSectionPath=""$sp""$csec""$sp""CSR"       >> ./Reaction/Auto.reaction
fi
echo -e "$sp""ShootLight=""$sp""1" 			  >> ./Reaction/Auto.reaction
echo -e "$sp""ShootHeavy=""$sp""0" 			  >> ./Reaction/Auto.reaction
#====================================================

echo "TARGET MATERIAL: ""$targetmaterial"

echo -e "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" 	>> ./Detector/Auto.detector
echo -e "Target"				>> ./Detector/Auto.detector
echo -e "  THICKNESS= ""$targT"" micrometer"	>> ./Detector/Auto.detector
echo -e "  ANGLE= 0 deg"			>> ./Detector/Auto.detector
echo -e "  RADIUS= 10 mm"			>> ./Detector/Auto.detector
#echo -e "  MATERIAL= CD2"			>> ./Detector/Auto.detector
echo -e "  MATERIAL= ""$targetmaterial"		>> ./Detector/Auto.detector
echo -e "  X= +0.00 millimeter"			>> ./Detector/Auto.detector
echo -e "  Y= +0.00 millimeter"			>> ./Detector/Auto.detector
echo -e "  Z= +0.00 millimeter"			>> ./Detector/Auto.detector
# - - - - - - - - - - - - - - - - - - - - - - - 

if [ "${13}" = "oneDet" ];
then
  echo -e "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"	>> ./Detector/Auto.detector
  echo -e "Mugast Annular"			>> ./Detector/Auto.detector
  echo -e " DetectorNumber = 10"		>> ./Detector/Auto.detector
  echo -e " Center = 0.0 0.0 ""$pos10"" mm" 	>> ./Detector/Auto.detector
  echo -e " Thickness = "$thick" mm"		>> ./Detector/Auto.detector
  echo -e " NumRing = "$nRing			>> ./Detector/Auto.detector
  echo -e " NumSector = "$nSect			>> ./Detector/Auto.detector
 

  newpos11=$((2*$pos11))
  echo -e "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"	>> ./Detector/Auto.detector
  echo -e "Mugast Annular"			>> ./Detector/Auto.detector
  echo -e " DetectorNumber = 11"		>> ./Detector/Auto.detector
  echo -e " Center = 0.0 0.0 ""$newpos11"" mm" 	>> ./Detector/Auto.detector
  echo -e " Thickness = 0.2 mm"		        >> ./Detector/Auto.detector
  echo -e " NumRing = 16"			>> ./Detector/Auto.detector
  echo -e " NumSector = 16"			>> ./Detector/Auto.detector

  newpos12=$((2*$pos12))

  echo -e "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"	>> ./Detector/Auto.detector
  echo -e "Mugast Annular"			>> ./Detector/Auto.detector
  echo -e " DetectorNumber = 12"		>> ./Detector/Auto.detector
  echo -e " Center = 0.0 0.0 ""$newpos12"" mm" 	>> ./Detector/Auto.detector
  echo -e " Thickness = 0.2 mm"			>> ./Detector/Auto.detector
  echo -e " NumRing = 16"			>> ./Detector/Auto.detector
  echo -e " NumSector = 16"			>> ./Detector/Auto.detector

  newpos13=$((2*$pos13))

  echo -e "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"	>> ./Detector/Auto.detector
  echo -e "Mugast Annular"			>> ./Detector/Auto.detector
  echo -e " DetectorNumber = 13"		>> ./Detector/Auto.detector
  echo -e " Center = 0.0 0.0 ""$newpos13"" mm" 	>> ./Detector/Auto.detector
  echo -e " Thickness = 0.2 mm"			>> ./Detector/Auto.detector
  echo -e " NumRing = 16"			>> ./Detector/Auto.detector
  echo -e " NumSector = 16"			>> ./Detector/Auto.detector




else
  echo -e "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"	>> ./Detector/Auto.detector
  echo -e "Mugast Annular"			>> ./Detector/Auto.detector
  echo -e " DetectorNumber =  10"		>> ./Detector/Auto.detector
  echo -e " Center = 0.0 0.0 ""$pos10"" mm" 	>> ./Detector/Auto.detector
  echo -e " Thickness = 0.5 mm" 		>> ./Detector/Auto.detector
  echo -e " NumRing = "$nRing			>> ./Detector/Auto.detector
  echo -e " NumSector = "$nSect			>> ./Detector/Auto.detector
  # - - - - - - - - - - - - - - - - - - - - - - - 
  echo -e "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"	>> ./Detector/Auto.detector
  echo -e "Mugast Annular"			>> ./Detector/Auto.detector
  echo -e " DetectorNumber = 11"		>> ./Detector/Auto.detector
  echo -e " Center = 0.0 0.0 ""$pos11"" mm" 	>> ./Detector/Auto.detector
  echo -e " Thickness = "$thick" mm"		>> ./Detector/Auto.detector
  echo -e " NumRing = 16"			>> ./Detector/Auto.detector
  echo -e " NumSector = 16"			>> ./Detector/Auto.detector
  # - - - - - - - - - - - - - - - - - - - - - - - 
  echo -e "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"	>> ./Detector/Auto.detector
  echo -e "Mugast Annular"			>> ./Detector/Auto.detector
  echo -e " DetectorNumber = 12"		>> ./Detector/Auto.detector
  echo -e " Center = 0.0 0.0 ""$pos12"" mm" 	>> ./Detector/Auto.detector
  echo -e " Thickness = "$thick" mm"		>> ./Detector/Auto.detector
  echo -e " NumRing = 16"			>> ./Detector/Auto.detector
  echo -e " NumSector = 16"			>> ./Detector/Auto.detector
  # - - - - - - - - - - - - - - - - - - - - - - - 
  echo -e "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"	>> ./Detector/Auto.detector
  echo -e "Mugast Annular"			>> ./Detector/Auto.detector
  echo -e " DetectorNumber = 13"		>> ./Detector/Auto.detector
  echo -e " Center = 0.0 0.0 ""$pos13"" mm" 	>> ./Detector/Auto.detector
  echo -e " Thickness = 3.0 mm"			>> ./Detector/Auto.detector
  echo -e " NumRing = 16"			>> ./Detector/Auto.detector
  echo -e " NumSector = 16"			>> ./Detector/Auto.detector

fi

echo -e "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"	>> ./Detector/Auto.detector
echo -e "ModularLeaf "				>> ./Detector/Auto.detector
echo -e "  DefaultValue= -5000"			>> ./Detector/Auto.detector
echo -e "  Leafs= GATCONF_MASTER CONFDEC_AGATA T_CATS2_HF T_MUGAST_CATS2 T_MUGAST_CATS2b E_AGATA T_FAG_CATS2 T_VAMOS_AGATA T_AGATA_CATS2 T_MUGAST_VAMOS T_MUGAST_AGATA T_VAMOS_CATS2 ">> ./Detector/Auto.detector
echo -e "  X= EVAMOS_AGATA   "			>> ./Detector/Auto.detector
echo -e "  Y= E_AGATA       "			>> ./Detector/Auto.detector

#====================================================
directory='/home/charlottepaxman/Programs/nptool/Outputs/Simulation/'

echo "Name: $nameconstruct"
echo "Reaction file: $rfile"
echo "Detector file: $dfile"


echo "TTreeName" >> RunToTreat_AutoGenerated.txt
echo " SimulatedTree" >> RunToTreat_AutoGenerated.txt
echo "RootFileName" >> RunToTreat_AutoGenerated.txt

START=1
END=${12}
mvnamesim_part="/media/charlottepaxman/Elements/ActiveWork/""$nameconstruct"

for (( x=$START; x<=$END; x++ ))
do
	outname=$nameconstruct"-"$x
	#npsimulation -D $dfile -E $rfile -B ./runsimulation_small.mac -O $outname;
	##npsimulation -D $dfile -E $rfile;
	##echo "$sp""../../Outputs/Simulation/""$outname"".root" >> RunToTreat_AutoGenerated.txt
  
	mv "../../Outputs/Simulation/""$nameconstruct""-""$x"".root" "$mvnamesim_part""-""$x"".root" 
	echo "$sp""$mvnamesim_part""-""$x"".root" >> RunToTreat_AutoGenerated.txt
done

outfile="Sim_"$nameconstruct
npanalysis --definition Sim --definition $6 -R RunToTreat_AutoGenerated.txt -E $rfile -D $dfile -O $outfile --definition ${10};

echo "-------------------------------"
echo "NPSimulation:  ""$mvnamesim_part""-##.root" 
echo "NPAnalysis:  "$mvname2
mv ../../Outputs/Analysis/Sim_GRIT* "$mvname2" 

#for (( x=$START; x<=$END; x++ ))
#do
#  echo "NPSimulation:  ""$mvnamesim_part""-""$x"".root" 
#  mv "../../Outputs/Simulation/""$nameconstruct""-""$x"".root" "$mvnamesim_part""-""$x"".root" 
#done

echo "-------------------------------"
